%Sample code
%Davor Curic, 2023, Complexity Science Group, University of Calgary
%
%This code loads the avalanches generated by 'generateAvalanches.m' and
%plots the initiation density maps


load('samplerecording_avalanches.mat') %this file is generated by 'generateAvalanches.m'
load("mask.mat")
corticalPixels = find(mask == 1); %these are the pixels corresponding to the cortical surface

%xmin is determined from loadAvalanches
smin = 0.002;
FOVsz = [128 128];

avSize = avalanches{1};
roots = avalanches{3};

clear profile frame

S = [];
count = 1;
profile = zeros(1, length(corticalPixels));
%for each avalanche collect their roots
for i = 1:length(avSize)
    for j = 1:length(avSize{i})
        if avSize{i}(j) < smin; continue; end
        frame = zeros(1, length(corticalPixels));
        frame([roots{i}{j}]) = 1;

        profile = profile + frame;
        count = count + 1;
    end
end
clear frame 
%convert the list of initations into XY
profile = embeddIntoFOV(profile'/count, corticalPixels, FOVsz);



%plot the initiation density
imagesc(log10(profile))
colorbar()
xticks([])
yticks([])